### ISSUE TITLE
Template compilation is broken when adding ember-cli-asset-sizes-shim

### ISSUE THREAD

**Issue by MiguelMadero** [isleofcode/ember-cli-asset-sizes-shim#5]
Normally the template will look something like:

```
define("spoof-ui/templates/index", ["exports"], function (exports) {
  exports["default"] =....
```

After adding this:

```
define("spoof-ui/templates/index", ["exports"], function (exports) {
  define("spoof-ui/templates/index", ["exports"], function (exports) { 
    exports["default"]
```

This breaks since we don't really have a template, but another function. 

I tested this with ember-cli 2.9.1 and ember 2.9.0 and 2.10-beta.1

**Comment by runspired** [comment]
@MiguelMadero confirm, I've warned about this before, it's sadly only useful to install, check sizes, uninstall, until I figure out what's broken where.

**Comment by MiguelMadero** [comment]
Ok. Sounds good. Thanks for confirming. Should I add a warning on the
README?
